version: "3.6"
services:
  master:
    build:
      context: .
      dockerfile: ./master/Dockerfile
    networks:
      app_net:
        ipv4_address: 172.18.0.254
  mapper:
    build:
      context: .
      dockerfile: ./mapper/Dockerfile
    networks:
      - app_net
#    ports:
#      - "8000:5000"
#  redis:
#    image: "redis:alpine"

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"

