version: "3.6"
services:
  master:
    build:
      context: .
      dockerfile: ./master/Dockerfile
  mapper:
    build:
      context: .
      dockerfile: ./mapper/Dockerfile
#    ports:
#      - "8000:5000"
#  redis:
#    image: "redis:alpine"

